include:
  - project: 'tech/templates'
    ref: $GLOBAL_REF_TEMPLATE
    file:
      - 'tarantool.template.yaml'
      # - '_group.deploy.yaml'

  - project: 'ecp/iis/iis-templates'
    ref:  master
    file: 'wf.template.yaml'
